/* eslint-disable @typescript-eslint/no-explicit-any */
import { Test } from '@nestjs/testing';
import {
  FallbackProviderModule,
  SimpleFallbackJsonRpcBatchProvider,
} from '../src';
import {
  fakeFetchImpl,
  fakeFetchImplThatAlwaysFails,
} from './fixtures/fake-json-rpc';
import { nullTransport, LoggerModule } from '@lido-nestjs/logger';
import { sleep } from './utils';
import { Network } from '@ethersproject/networks';

/**
 * Provider selection when some fallback providers are invalid.
 *
 * A provider is "invalid" for the `provider` getter when its network is
 * null or has a wrong chainId. This is a real, reachable state: if an
 * endpoint is down when the process starts, `detectNetwork` leaves its
 * network as null (and, since results are cached, it stays null for the
 * lifetime of the process). The daemon then runs fine on the remaining
 * providers — until request routing has to step onto the invalid one.
 *
 * The getter skips invalid providers with a wrap-around scan. Before the
 * wrap-around, a plain increment walked past the array end whenever the
 * scan started at the LAST provider and it was invalid:
 *
 *   1. `fallbackProviders[length]` is undefined → `isValid(undefined)`
 *      throws a TypeError before any HTTP request is formed;
 *   2. the crash leaves the index at `length`; `switchToNextProvider`
 *      in the perform catch block does `(length + 1) % length`, which
 *      skips provider 0 and lands back on the same invalid provider;
 *   3. goto 1 — every request fails until restart, even though a healthy
 *      provider sits at a lower index the whole time.
 *
 * These tests pin the fixed behavior: for every combination of validity
 * and starting index the scan terminates on a provider, and requests are
 * actually served by a healthy one.
 */

type ProviderInternals = SimpleFallbackJsonRpcBatchProvider & {
  fallbackProviders: {
    provider: { fetchJson: (...args: unknown[]) => Promise<unknown> };
    network: Network | null;
    index: number;
  }[];
  activeFallbackProviderIndex: number;
};

const MAINNET: Network = { name: 'homestead', chainId: 1 };

describe('SimpleFallbackJsonRpcBatchProvider provider selection', () => {
  let provider: ProviderInternals;
  let fetchMocks: jest.SpyInstance[];

  const createProvider = async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [
        FallbackProviderModule.forFeature({
          imports: [LoggerModule.forRoot({ transports: [nullTransport()] })],
          // two providers: the minimum where the scan can start at the last
          // index and overflow; also the most common production setup
          urls: ['http://localhost:1001', 'http://localhost:1002'],
          network: 1,
          // the worst case for selection: the retrier gives no second chance
          // inside a perform attempt (src/common/retrier.ts:39 — with
          // maxRetryCount <= 1 the error is rethrown immediately), so
          // selection must route correctly on the first try. With
          // maxRetries >= 2 the old overflow was masked: the crash left the
          // index out of bounds, the in-perform retry re-entered the getter
          // and its entry guard reset the index to 0 — see the comment on
          // the guard in src/provider/simple-fallback-json-rpc-batch-provider.ts:258
          maxRetries: 1,
          minBackoffMs: 10,
          maxBackoffMs: 1000,
          logRetries: false,
          requestPolicy: {
            jsonRpcMaxBatchSize: 1,
            batchAggregationWaitMs: 10,
            maxConcurrentRequests: 1,
          },
        }),
      ],
    }).compile();

    provider = moduleRef.get(
      SimpleFallbackJsonRpcBatchProvider,
    ) as ProviderInternals;

    fetchMocks = provider.fallbackProviders.map((fallback, i) =>
      jest
        .spyOn(fallback.provider as any, 'fetchJson')
        .mockImplementation(fakeFetchImpl(1, 10001 + i) as any),
    );

    // ethers v5 JsonRpcProvider constructor auto-detects the network via
    // setTimeout(0); wait it out and drop its fetch calls so the assertions
    // below count only the traffic generated by the test itself
    await sleep(50);
    fetchMocks.forEach((mock) => mock.mockClear());
  };

  // Puts the provider into the state under test directly. `network: null`
  // is exactly what `detectNetwork` leaves behind for an endpoint that was
  // down at process start; setting it by hand keeps the tests focused on
  // selection instead of re-deriving the state through failed HTTP probes.
  const setProviderState = (valid: [boolean, boolean], activeIndex: number) => {
    provider.fallbackProviders[0].network = valid[0] ? MAINNET : null;
    provider.fallbackProviders[1].network = valid[1] ? MAINNET : null;
    provider.activeFallbackProviderIndex = activeIndex;
  };

  afterEach(async () => {
    await sleep(0);
    jest.resetAllMocks();
  });

  // Exhaustive scan check: every (starting index × validity) combination
  // must terminate on a provider and leave the index in bounds.
  // - scans starting at index 0 always worked (the walk-up reaches
  //   provider 1 before running out of array);
  // - scans starting at index 1 with provider 1 invalid are the rows that
  //   used to read fallbackProviders[2] = undefined and throw a TypeError;
  // - when ALL providers are invalid, the last examined one is returned:
  //   the request is still attempted for real (the child provider does not
  //   depend on the `network` mark), so it either succeeds or fails with a
  //   real network error instead of a synthetic crash
  test.each([
    { activeIndex: 0, valid: [true, true], returnsIndex: 0 },
    { activeIndex: 0, valid: [true, false], returnsIndex: 0 },
    { activeIndex: 0, valid: [false, true], returnsIndex: 1 },
    { activeIndex: 0, valid: [false, false], returnsIndex: 1 },
    { activeIndex: 1, valid: [true, true], returnsIndex: 1 },
    { activeIndex: 1, valid: [false, true], returnsIndex: 1 },
    { activeIndex: 1, valid: [true, false], returnsIndex: 0 },
    { activeIndex: 1, valid: [false, false], returnsIndex: 0 },
  ] as { activeIndex: number; valid: [boolean, boolean]; returnsIndex: number }[])(
    'activeIndex=$activeIndex, valid=$valid → provider $returnsIndex',
    async ({ activeIndex, valid, returnsIndex }) => {
      await createProvider();
      setProviderState(valid, activeIndex);

      // the getter mutates the active index — read it exactly once
      const returned: { index: number } = (provider as any).provider;

      expect(returned.index).toBe(returnsIndex);
      expect(provider.activeFallbackProviderIndex).toBeLessThan(2);
    },
  );

  // Steady state under the bug: the fallback endpoint was down at process
  // start (network never detected) and the active index points at it —
  // e.g. left there by an earlier switch. Every request must be served by
  // the healthy provider 0. Before the wrap-around this exact state
  // crash-looped: TypeError in the getter before any HTTP request, the
  // index oscillating between 1 and 2, provider 0 never asked.
  test('routes requests around an invalid active provider to a healthy one', async () => {
    await createProvider();
    setProviderState([true, false], 1);

    for (let i = 0; i < 3; i++) {
      await expect(provider.perform('getBlockNumber', {})).resolves.toBe(
        '0x2710',
      );
      // selection settles on the healthy provider, not back on the invalid one
      expect(provider.activeFallbackProviderIndex).toBe(0);
    }

    expect(fetchMocks[0]).toHaveBeenCalledTimes(3); // one request per perform
    expect(fetchMocks[1]).toHaveBeenCalledTimes(0); // invalid provider skipped
  });

  // The trigger sequence: everything runs on healthy provider 0 until a
  // single transient network error makes the perform catch block switch to
  // the invalid provider 1. The very next attempt inside the same perform
  // must wrap around back to provider 0 and succeed — one failed attempt,
  // not a permanent outage. Before the wrap-around this switch was the
  // point of no return: from here on every request crash-looped forever
  // while both endpoints were reachable.
  test('recovers within one perform when a transient error switches onto an invalid provider', async () => {
    await createProvider();
    setProviderState([true, false], 0);

    // attempt 1 fails and switches 0 → 1; attempt 2 wraps 1 → 0 and succeeds
    fetchMocks[0].mockImplementationOnce(fakeFetchImplThatAlwaysFails);
    await expect(provider.perform('getBlockNumber', {})).resolves.toBe(
      '0x2710',
    );

    expect(provider.activeFallbackProviderIndex).toBe(0);
    expect(fetchMocks[1]).toHaveBeenCalledTimes(0);
  });
});
