name: test
on: pull_request
jobs:
  test-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate types
        run: yarn typechain
      - name: Run lint
        run: yarn lint
      - name: Build Components
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
        env:
          EL_RPC_URL: ${{ secrets.EL_RPC_URL }}
